server:
  port: 8080

spring:
  application:
    name: proyecto-integrador
  h2:
    console:
      enabled: true
      path: /console/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:umbrellabd
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop