server:
  port: 8080

spring:
  application:
    name: proyecto-integrador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ticketgo.c1sa0i26gqfq.us-east-1.rds.amazonaws.com:3306/TICKETGO
    username: admin
    password: dh_ticketgo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect