name: Build and Deploy to ec2

on:
  push:
    branches:
      - main  # Ejecutar el pipeline cuando se hace push a la rama principal
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECR_REPO_NAME: 'ticketgo'
  AWS_ECR_REPO_LINK: '970547369787.dkr.ecr.us-east-1.amazonaws.com/ticketgo'
  AWS_ECR_REPO_PATH: '970547369787.dkr.ecr.us-east-1.amazonaws.com'
  USERNAME : 'juanleongo'
  CONTRA: 'Lomasfresa420'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run all tests
        run: ./gradlew testClasses

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Login to docker hub
        run: docker login -u ${{env.USERNAME}} -p ${{env.CONTRA}}
      - name: Build docker image
        run: docker build -t juanleongo/ticketgo .
      - name: Publish image to docker hub
        run: docker push juanleongo/ticketgo:latest
      - name: cambiar directorio
        run: cd actions-runner/
      - name: Publish image to docker hub
        run: ./run.sh

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull juanleongo/ticketgo:latest
      - name: Delete old container
        run: sudo docker rm -f ticketgo-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name ticketgo-container juanleongo/ticketgo
