name: Build and Deploy to EB

on:
  push:
    branches:
      - main  # Ejecutar el pipeline cuando se hace push a la rama principal
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECR_REPO_NAME: 'ticketgo'
  AWS_ECR_REPO_LINK: '970547369787.dkr.ecr.us-east-1.amazonaws.com/ticketgo'
  AWS_ECR_REPO_PATH: '970547369787.dkr.ecr.us-east-1.amazonaws.com'
  AWS_ECS_CLUSTER_NAME: 'back-ticketgo'
  AWS_ECS_SERVICE_NAME: 'back-ticketgo'
  USERNAME : 'juanleongo'
  CONTRA: 'Lomasfresa420'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{env.USERNAME}} -p ${{env.CONTRA}}
      - name: Build docker image
        run: docker build -t juanleongo/ticketgo .
      - name: Publish image to docker hub
        run: docker push juanleongo/ticketgo:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull juanleongo/ticketgo:latest
      - name: Delete old container
        run: docker rm -f ticketgo-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name ticketgo-container juanleongo/ticketgo
